# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fund_clearing_python_sdk
from fund_clearing_python_sdk.api.transfer_request_api import TransferRequestApi  # noqa: E501
from fund_clearing_python_sdk.rest import ApiException


class TestTransferRequestApi(unittest.TestCase):
    """TransferRequestApi unit test stubs"""

    def setUp(self):
        self.api = fund_clearing_python_sdk.api.transfer_request_api.TransferRequestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_transfer_request_create(self):
        """Test case for transfer_request_create

        Create a new instance of the model and persist it into the data source.  # noqa: E501
        """
        pass

    def test_transfer_request_delete_by_id(self):
        """Test case for transfer_request_delete_by_id

        Delete a model instance by {{id}} from the data source.  # noqa: E501
        """
        pass

    def test_transfer_request_exists(self):
        """Test case for transfer_request_exists

        Check whether a model instance exists in the data source.  # noqa: E501
        """
        pass

    def test_transfer_request_find(self):
        """Test case for transfer_request_find

        Find all instances of the model matched by filter from the data source.  # noqa: E501
        """
        pass

    def test_transfer_request_find_by_id(self):
        """Test case for transfer_request_find_by_id

        Find a model instance by {{id}} from the data source.  # noqa: E501
        """
        pass

    def test_transfer_request_replace_by_id(self):
        """Test case for transfer_request_replace_by_id

        Replace attributes for a model instance and persist it into the data source.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
