# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fund_clearing_python_sdk
from fund_clearing_python_sdk.api.system_api import SystemApi  # noqa: E501
from fund_clearing_python_sdk.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = fund_clearing_python_sdk.api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_system_bind_identity(self):
        """Test case for system_bind_identity

        Bind an identity to the specified participant  # noqa: E501
        """
        pass

    def test_system_get_all_historian_records(self):
        """Test case for system_get_all_historian_records

        Get all Historian Records from the Historian  # noqa: E501
        """
        pass

    def test_system_get_all_identities(self):
        """Test case for system_get_all_identities

        Get all identities from the identity registry  # noqa: E501
        """
        pass

    def test_system_get_historian_record_by_id(self):
        """Test case for system_get_historian_record_by_id

        Get the specified Historian Record from the Historian  # noqa: E501
        """
        pass

    def test_system_get_identity_by_id(self):
        """Test case for system_get_identity_by_id

        Get the specified identity from the identity registry  # noqa: E501
        """
        pass

    def test_system_issue_identity(self):
        """Test case for system_issue_identity

        Issue an identity to the specified participant  # noqa: E501
        """
        pass

    def test_system_ping(self):
        """Test case for system_ping

        Test the connection to the business network  # noqa: E501
        """
        pass

    def test_system_revoke_identity(self):
        """Test case for system_revoke_identity

        Revoke the specified identity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
