# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fund_clearing_python_sdk
from fund_clearing_python_sdk.models.banking_participant import BankingParticipant  # noqa: E501
from fund_clearing_python_sdk.rest import ApiException


class TestBankingParticipant(unittest.TestCase):
    """BankingParticipant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankingParticipant(self):
        """Test BankingParticipant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fund_clearing_python_sdk.models.banking_participant.BankingParticipant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
