# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fund_clearing_python_sdk
from fund_clearing_python_sdk.models.create_batch import CreateBatch  # noqa: E501
from fund_clearing_python_sdk.rest import ApiException


class TestCreateBatch(unittest.TestCase):
    """CreateBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBatch(self):
        """Test CreateBatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = fund_clearing_python_sdk.models.create_batch.CreateBatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
