# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import fund_clearing_python_sdk
from fund_clearing_python_sdk.api.complete_settlement_api import CompleteSettlementApi  # noqa: E501
from fund_clearing_python_sdk.rest import ApiException


class TestCompleteSettlementApi(unittest.TestCase):
    """CompleteSettlementApi unit test stubs"""

    def setUp(self):
        self.api = fund_clearing_python_sdk.api.complete_settlement_api.CompleteSettlementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_complete_settlement_create(self):
        """Test case for complete_settlement_create

        Create a new instance of the model and persist it into the data source.  # noqa: E501
        """
        pass

    def test_complete_settlement_find(self):
        """Test case for complete_settlement_find

        Find all instances of the model matched by filter from the data source.  # noqa: E501
        """
        pass

    def test_complete_settlement_find_by_id(self):
        """Test case for complete_settlement_find_by_id

        Find a model instance by {{id}} from the data source.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
