# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IssueIdentityRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant': 'str',
        'user_id': 'str',
        'options': 'object'
    }

    attribute_map = {
        'participant': 'participant',
        'user_id': 'userID',
        'options': 'options'
    }

    def __init__(self, participant=None, user_id=None, options=None):  # noqa: E501
        """IssueIdentityRequest - a model defined in Swagger"""  # noqa: E501

        self._participant = None
        self._user_id = None
        self._options = None
        self.discriminator = None

        self.participant = participant
        self.user_id = user_id
        if options is not None:
            self.options = options

    @property
    def participant(self):
        """Gets the participant of this IssueIdentityRequest.  # noqa: E501


        :return: The participant of this IssueIdentityRequest.  # noqa: E501
        :rtype: str
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this IssueIdentityRequest.


        :param participant: The participant of this IssueIdentityRequest.  # noqa: E501
        :type: str
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant

    @property
    def user_id(self):
        """Gets the user_id of this IssueIdentityRequest.  # noqa: E501


        :return: The user_id of this IssueIdentityRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this IssueIdentityRequest.


        :param user_id: The user_id of this IssueIdentityRequest.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def options(self):
        """Gets the options of this IssueIdentityRequest.  # noqa: E501


        :return: The options of this IssueIdentityRequest.  # noqa: E501
        :rtype: object
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this IssueIdentityRequest.


        :param options: The options of this IssueIdentityRequest.  # noqa: E501
        :type: object
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IssueIdentityRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
