# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MarkPreProcessComplete(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_class': 'str',
        'batch_id': 'str',
        'transaction_id': 'str',
        'timestamp': 'datetime'
    }

    attribute_map = {
        '_class': '$class',
        'batch_id': 'batchId',
        'transaction_id': 'transactionId',
        'timestamp': 'timestamp'
    }

    def __init__(self, _class='org.clearing.MarkPreProcessComplete', batch_id=None, transaction_id=None, timestamp=None):  # noqa: E501
        """MarkPreProcessComplete - a model defined in Swagger"""  # noqa: E501

        self.__class = None
        self._batch_id = None
        self._transaction_id = None
        self._timestamp = None
        self.discriminator = None

        if _class is not None:
            self._class = _class
        self.batch_id = batch_id
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def _class(self):
        """Gets the _class of this MarkPreProcessComplete.  # noqa: E501

        The class identifier for this type  # noqa: E501

        :return: The _class of this MarkPreProcessComplete.  # noqa: E501
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """Sets the _class of this MarkPreProcessComplete.

        The class identifier for this type  # noqa: E501

        :param _class: The _class of this MarkPreProcessComplete.  # noqa: E501
        :type: str
        """

        self.__class = _class

    @property
    def batch_id(self):
        """Gets the batch_id of this MarkPreProcessComplete.  # noqa: E501


        :return: The batch_id of this MarkPreProcessComplete.  # noqa: E501
        :rtype: str
        """
        return self._batch_id

    @batch_id.setter
    def batch_id(self, batch_id):
        """Sets the batch_id of this MarkPreProcessComplete.


        :param batch_id: The batch_id of this MarkPreProcessComplete.  # noqa: E501
        :type: str
        """
        if batch_id is None:
            raise ValueError("Invalid value for `batch_id`, must not be `None`")  # noqa: E501

        self._batch_id = batch_id

    @property
    def transaction_id(self):
        """Gets the transaction_id of this MarkPreProcessComplete.  # noqa: E501

        The instance identifier for this type  # noqa: E501

        :return: The transaction_id of this MarkPreProcessComplete.  # noqa: E501
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this MarkPreProcessComplete.

        The instance identifier for this type  # noqa: E501

        :param transaction_id: The transaction_id of this MarkPreProcessComplete.  # noqa: E501
        :type: str
        """

        self._transaction_id = transaction_id

    @property
    def timestamp(self):
        """Gets the timestamp of this MarkPreProcessComplete.  # noqa: E501


        :return: The timestamp of this MarkPreProcessComplete.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this MarkPreProcessComplete.


        :param timestamp: The timestamp of this MarkPreProcessComplete.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarkPreProcessComplete):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
