# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PingResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant': 'str',
        'identity': 'str',
        'version': 'str'
    }

    attribute_map = {
        'participant': 'participant',
        'identity': 'identity',
        'version': 'version'
    }

    def __init__(self, participant=None, identity=None, version=None):  # noqa: E501
        """PingResponse - a model defined in Swagger"""  # noqa: E501

        self._participant = None
        self._identity = None
        self._version = None
        self.discriminator = None

        if participant is not None:
            self.participant = participant
        if identity is not None:
            self.identity = identity
        self.version = version

    @property
    def participant(self):
        """Gets the participant of this PingResponse.  # noqa: E501


        :return: The participant of this PingResponse.  # noqa: E501
        :rtype: str
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this PingResponse.


        :param participant: The participant of this PingResponse.  # noqa: E501
        :type: str
        """

        self._participant = participant

    @property
    def identity(self):
        """Gets the identity of this PingResponse.  # noqa: E501


        :return: The identity of this PingResponse.  # noqa: E501
        :rtype: str
        """
        return self._identity

    @identity.setter
    def identity(self, identity):
        """Sets the identity of this PingResponse.


        :param identity: The identity of this PingResponse.  # noqa: E501
        :type: str
        """

        self._identity = identity

    @property
    def version(self):
        """Gets the version of this PingResponse.  # noqa: E501


        :return: The version of this PingResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PingResponse.


        :param version: The version of this PingResponse.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PingResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
