# coding: utf-8

"""
    LoopBack Application

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UsdExchangeRate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_class': 'str',
        'to': 'str',
        'rate': 'float',
        'id': 'str'
    }

    attribute_map = {
        '_class': '$class',
        'to': 'to',
        'rate': 'rate',
        'id': 'id'
    }

    def __init__(self, _class='org.clearing.UsdExchangeRate', to=None, rate=None, id=None):  # noqa: E501
        """UsdExchangeRate - a model defined in Swagger"""  # noqa: E501

        self.__class = None
        self._to = None
        self._rate = None
        self._id = None
        self.discriminator = None

        if _class is not None:
            self._class = _class
        self.to = to
        self.rate = rate
        if id is not None:
            self.id = id

    @property
    def _class(self):
        """Gets the _class of this UsdExchangeRate.  # noqa: E501

        The class identifier for this type  # noqa: E501

        :return: The _class of this UsdExchangeRate.  # noqa: E501
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """Sets the _class of this UsdExchangeRate.

        The class identifier for this type  # noqa: E501

        :param _class: The _class of this UsdExchangeRate.  # noqa: E501
        :type: str
        """

        self.__class = _class

    @property
    def to(self):
        """Gets the to of this UsdExchangeRate.  # noqa: E501


        :return: The to of this UsdExchangeRate.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this UsdExchangeRate.


        :param to: The to of this UsdExchangeRate.  # noqa: E501
        :type: str
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    @property
    def rate(self):
        """Gets the rate of this UsdExchangeRate.  # noqa: E501


        :return: The rate of this UsdExchangeRate.  # noqa: E501
        :rtype: float
        """
        return self._rate

    @rate.setter
    def rate(self, rate):
        """Sets the rate of this UsdExchangeRate.


        :param rate: The rate of this UsdExchangeRate.  # noqa: E501
        :type: float
        """
        if rate is None:
            raise ValueError("Invalid value for `rate`, must not be `None`")  # noqa: E501

        self._rate = rate

    @property
    def id(self):
        """Gets the id of this UsdExchangeRate.  # noqa: E501


        :return: The id of this UsdExchangeRate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UsdExchangeRate.


        :param id: The id of this UsdExchangeRate.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsdExchangeRate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
